[package]
name = "chromiumoxide_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chromiumoxide = "0.3.4"
futures = "*"
tokio = {version = "*", features = ["macros", "rt-multi-thread"]}
